### ISSUE TITLE
Configuration property "camera.videoWidth" is not defined

### ISSUE THREAD

**Issue by Elvincth** [stetsmando/pi-motion-detection#4]
Configuration property "camera.videoWidth" is not defined

**Comment by stetsmando** [comment]
This library isn't actively maintained. I haven't had this code running in about a year so I can't really debug it. Sorry!

**Comment by jonesg504** [comment]
Hey I figured out a solution to this error, include a /config directory in your root directory wherever you are running the code and then include a default.json with:
```
{
    "camera": {
        "photoTimeout": 1000,
        "photoWidth": 100,
        "photoHeight": 100,

        "videoTimeout": 5000,
        "videoWidth": 1920,
        "videoHeight": 1080,

        "compareThreshold": 0.1
    }
}
```
